### ISSUE TITLE
Add source url to the depends edge between modules.

### ISSUE THREAD

**Issue by mjpitz** [deps-cloud/tracker#41]
This will allow us to track unique dependencies per repository and help solve the conflict errors when indexing multiple repositories that produce the "same" module. e.g. forks

**Comment by MadhuvanthG** [comment]
@mjpitz I have made my initial analysis and would like to discuss the findings with you, before I proceed with code changes. 

If I've to split the requirement into two parts-

1. #### Track unique dependencies per repo - 
Right now, dependencies are tracked per "module" and that doesn't allow us to clearly map dependencies to a repo (for example, `deps-cloud/tracker` & `<forked-repo>/tracker` produce the same module, but they could have different dependencies)

2. #### Conflict errors when indexing multiple repo that produce the "same" module - 
I don't understand this fully, as the indexing service seems to operate on repo URLs. Can you expand on what errors are we talking about?

**Comment by MadhuvanthG** [comment]
**Analysis on the work that needs to be done:**

1. ##### `Track` rpc method in `SourceService`: 
While storing the dependencies, we need to store the source (a.k.a repo) URL as well. 

2. ##### `ListDependencies` rpc method in `DependencyService`: 
Make changes here to produce the source URL while serving `/v1alpha/graph/{language}/dependencies` endpoint

**Comment by mjpitz** [comment]
@MadhuvanthG you're pretty much spot on with your analysis. I spent some time thinking about this the other day. The way the data is represented in the database assumes a single edge between modules. My initial thought was to update the data model to support multiple edges between the same pair of nodes. To do this, you would have to update the DB schema. This is where I get stuck a lot of the time. Right now, the database model is as follows:

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcblNvdXJjZSAtLT58TWFuYWdlc3wgTW9kdWxlXG5Nb2R1bGUgLS0-fERlcGVuZHN8IE1vZHVsZVxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcblNvdXJjZSAtLT58TWFuYWdlc3wgTW9kdWxlXG5Nb2R1bGUgLS0-fERlcGVuZHN8IE1vZHVsZVxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

This structure is represented in the database in a single table:
https://github.com/deps-cloud/tracker/blob/master/pkg/services/graphstore/statements.go#L24-L31

The important things to note about this schema:
* when k1 == k2, the data is a node
* when k1 != k2, the data is an edge
  * k1 is the key of the originating node and k2 is the key of the target node
  * This allows us to implicitly module directionality

**Comment by mjpitz** [comment]
My thought was:
1. update the schema to support a k3 (nullable, used as keying material on edges) (1 change to deps-cloud/api)
2. modify the corresponding RPCs to support the new model (1 change to deps-cloud/tracker)

**Comment by mjpitz** [comment]
Heads up, I'm going to be working in some similar terratory while working on https://github.com/deps-cloud/tracker/issues/43.

**Comment by MadhuvanthG** [comment]
Thank you for the details. I'm going to spend some time understanding how the model is represented in the database and then make changes. 

I guess, I'll have questions as I go about it. Do you think gitter is a better place or right here?

**Comment by mjpitz** [comment]
Lets have some conversation here. I've been following along with my inbox here a bit better.

**Comment by MadhuvanthG** [comment]
So I now understand the data-model a lot better. I also think, we will have to add support for multiple edges between modules and on the `depends` edge, store the source URL in k3. 

That means, we will have to change the DB schema. I actually don't see a better way (i.e. without changing the DB schema) here.

**Comment by MadhuvanthG** [comment]
Are you already at changing the schema? If so, I'm happy to wait and leverage the new key (k3) to store the source URL, so we could complete this issue too.

**Comment by MadhuvanthG** [comment]
@mjpitz, I started with the implementation. This is how I'm heading and need some help.

> update the schema to support a k3 (nullable, used as keying material on edges) (1 change to deps-cloud/api)

After adding a `k3` to the `store.proto`, **do we have a script (or a protoc command) to regenerate the protocol buffer classes**? Can you point me to that?

> modify the corresponding RPCs to support the new model (1 change to deps-cloud/tracker)

Conceptualized the changes required to the different RPCs and I'm fairly comfortable here. I suppose, I could build the local `tracker` image pointing to the local `/api` module by doing something like [this](https://medium.com/@teivah/how-to-test-a-local-branch-with-go-mod-54df087fc9cc) and test my changes. 

So if you could help me out with regenerating the protobuf classes in `/api`, it would get me moving forward.

**Comment by mjpitz** [comment]
@MadhuvanthG there's a make target that will spin up a docker image to do the code generation. You'll need to update the typescript defs by hand

**Comment by mjpitz** [comment]
For testing, I like the approach of using `go mod vendor` then building the image that way.

**Comment by MadhuvanthG** [comment]
> @MadhuvanthG there's a make target that will spin up a docker image to do the code generation. You'll need to update the typescript defs by hand

Hmm, I run into some error while using `compile-docker`. Let me know if you're able to point out anything obvious with the error in this screenshot (the repo name is indeed lower-case; **api**) , else I'll dig into this tomorrow. 

<img width="957" alt="Screen Shot 2020-05-01 at 9 43 41 PM" src="https://user-images.githubusercontent.com/48177081/80820616-dd577980-8bf4-11ea-86b3-d8b3ef81fbdc.png">

**Comment by MadhuvanthG** [comment]
deps-cloud/deps.cloud#7

**Comment by MadhuvanthG** [comment]
@mjpitz, Please review the linked PR here and the one for change in `/api` (linked in the parent issue deps-cloud/deps.cloud#7)

**Comment by MadhuvanthG** [comment]
For testing, this is how I built the `tracker` image pointing to the local `api` package, but I think there is a cleaner way. Can you point me in the right direction please?

1. Ran the command `go mod vendor` with a replace line in go.mod
    `replace github.com/deps-cloud/api => /local-repo-path/deps.cloud_all_repos/api`
   This built the dependencies in a `/vendor` folder

2. Built the image using `make docker` target. However, did a few changes:
     - Skipped `make deps`
     - added a `-mod=vendor` flag to `go install` to reference deps from the `/vendor` directory

This also causes the tests/linting to fail.

**Comment by MadhuvanthG** [comment]
So the open PR does add support to have multiple depends edges between modules. As next steps for this issue, we got to store the sourceURL on the depends edge, so we could return them in our endpoints.

I'm thinking, `scopes` field on the `depends` schema is appropriate to store the sourceURL. Result of the `dependencies` endpoint would then look like this, for example:

```
"dependencies": [
         {
           "depends": {
                  "language": "go",
                  "version_constraint": "v1.3.0",
                   "scopes": [
                           "direct",
                           "https://github.com/deps-cloud/tracker.git"
                  ]
             },
          ....
          ...
      },
          {
           "depends": {
                  "language": "go",
                  "version_constraint": "v1.3.0",
                   "scopes": [
                           "direct",
                           "https://github.com/MadhuvanthG/tracker.git"
                  ]
             },
          ....
          ...
      },
},
```

Thoughts, @mjpitz?

**Comment by mjpitz** [comment]
I wouldn't use scopes for something like this. Scopes was intended to represent the scope of the dependency (compile time vs test only etc).

Can we add a `ref` field to the depends edge and have that be the source URL?

**Comment by MadhuvanthG** [comment]
Now that I understand the intention behind `scopes`, makes a lot of sense. Sure, will work on it.

**Comment by MadhuvanthG** [comment]
@mjpitz, this is not fully done yet, needs one minor change to tracker to store the source URL. Waiting on a new version of `api` with new fields in this PR deps-cloud/api#10

**Comment by MadhuvanthG** [comment]
Also, if you could help me with this, it would be great.

> For testing, this is how I built the `tracker` image pointing to the local `api` package.
> 
> 1. Ran the command `go mod vendor` with a replace line in go.mod
>    `replace github.com/deps-cloud/api => /local-repo-path/deps.cloud_all_repos/api`
>    This built the dependencies in a `/vendor` folder
> 2. Built the image using `make docker` target. However, did a few changes:
>    
>    * Skipped `make deps`
>    * added a `-mod=vendor` flag to `go install` to reference deps from the `/vendor` directory
> 
> It worked but I think there is a cleaner way. This also causes the tests/linting to fail. Can you point me in the right direction please?
