### ISSUE TITLE
Separate sql statements for MySQL to improve performance

### ISSUE THREAD

**Issue by MadhuvanthG** [deps-cloud/tracker#54]
While the queries work for mysql, the insert isn't performant. We should be able to do an `INSERT ON DUPLICATE KEY UPDATE` for MySQL. This capability is not available in sqlite which is why the original statement was written using `REPLACE INTO` which is the functional equivalent of doing a delete and re-insert regardless if the data changed. This causes compounding writes and the MySQL indexes can be overloaded during indexing.

_Originally posted by @mjpitz in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjY5ODYxNDk2OnYy/pull_request_review_threads/discussion_

**Comment by mjpitz** [comment]
@MadhuvanthG I've got a change slated for this as part of another change where I was adding an index on date_deleted.
